import { useEffect, useMemo, useRef, useState } from 'react';
import { blankProject, blankSegment, now, splitText, type Project, type Workspace } from './model';
import { loadWorkspace, saveWorkspace } from './storage';
import './writer-v3.css';

type Mode='original'|'expanded'|'final';
type Stage='polish'|'review'|'quality';
type Finding={term:string;count:number;snippets:string[]};
const count=(s:string)=>s.length;
const esc=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const fileTitle=(name:string)=>name.replace(/\.[^.]+$/,'');
const collator=new Intl.Collator('ko',{numeric:true,sensitivity:'base'});
const naturalSort=(a:File,b:File)=>collator.compare(a.name,b.name);
const sortedSegments=(p:Project)=>[...p.segments].filter(x=>x.kind==='회차'||x.kind==='장면').sort((a,b)=>collator.compare(a.title,b.title));
function repeatFindings(text:string,custom:string,threshold=3):Finding[]{const terms=new Set(custom.split(/[\n,/]/).map(x=>x.trim()).filter(x=>x.length>=2));const tokens=text.match(/[가-힣A-Za-z]{2,}/g)||[],freq=new Map<string,number>();tokens.forEach(t=>freq.set(t,(freq.get(t)||0)+1));[...freq].filter(([,n])=>n>=Math.max(4,threshold)).sort((a,b)=>b[1]-a[1]).slice(0,24).forEach(([t])=>terms.add(t));return [...terms].map(term=>{const re=new RegExp(esc(term),'g'),n=(text.match(re)||[]).length;if(n<threshold)return null;const snippets:string[]=[];let m:RegExpExecArray|null;while((m=re.exec(text))&&snippets.length<5){snippets.push(text.slice(Math.max(0,m.index-50),Math.min(text.length,m.index+term.length+60)).replace(/\s+/g,' '));if(re.lastIndex===m.index)re.lastIndex++;}return{term,count:n,snippets}}).filter(Boolean).sort((a,b)=>b!.count-a!.count) as Finding[]}
function phraseFindings(text:string,raw:string):Finding[]{return raw.split(/[\n,]/).map(x=>x.trim()).filter(x=>x.length>=2).map(term=>{const re=new RegExp(esc(term),'g'),n=(text.match(re)||[]).length;if(!n)return null;const snippets:string[]=[];let m:RegExpExecArray|null;while((m=re.exec(text))&&snippets.length<4)snippets.push(text.slice(Math.max(0,m.index-45),Math.min(text.length,m.index+term.length+55)).replace(/\s+/g,' '));return{term,count:n,snippets}}).filter(Boolean) as Finding[]}
function reviewPrompt(term:string,selected:string,text:string,criteria=''){const target=selected.trim()||term,i=selected.trim()?text.indexOf(selected):text.indexOf(term),a=Math.max(0,i-600),b=Math.min(text.length,(i<0?0:i+target.length)+600);return `장편소설 퇴고 중입니다. 아래 부분을 보수적으로 검토해 주세요.\n\n[작품 검수 기준]\n${criteria||'별도 기준 없음'}\n\n[확인 이유]\n${term}\n\n[수정 대상]\n${target}\n\n[앞뒤 문맥]\n${text.slice(a,b)}\n\n[원칙]\n- 기준집을 우선 적용하되 무조건 수정하지 말고 실제로 거슬릴 때만 수정\n- 사건, 설정, 캐릭터 성격과 감정 진행 속도 유지\n- 과한 감정 추가, 새 설정 추가, 전면 재작성 금지\n- 원문 유지가 더 좋다면 유지 추천이라고 명시\n\n[답변]\n1. 수정 필요 여부\n2. 어떤 기준에 걸렸는지\n3. 이유\n4. 필요할 때만 수정안 1~3개`}
function criteriaReviewPrompt(text:string,criteria:string){return `아래 장편소설 원고를 [작품 검수 기준]에 맞춰 1차 검수해 주세요.\n\n[작품 검수 기준]\n${criteria||'등록된 기준 없음'}\n\n[검수 대상]\n다듬는 원고\n\n[중요]\n- 기준에 적혀 있다는 이유만으로 억지로 문제를 만들지 말 것\n- 실제 독서 흐름에서 거슬리는 항목만 지적할 것\n- 반복, AI스러운 과감정, 설명 과다, 경직 문장, 캐릭터 불일치, 설정 오류, 감정 연결 문제를 기준집과 함께 볼 것\n- 새 설정을 추가하거나 감정 속도를 앞당기지 말 것\n- 문제없으면 문제없다고 할 것\n\n[출력]\n1. 필수 확인\n2. 선택 확인\n3. 유지 권장\n각 항목에 해당 기준과 원문 위치를 짧게 표시할 것.\n\n[원고]\n${text}`}
function qualityPrompt(text:string,criteria=''){return `아래 장편소설 원고에서 단순히 분량을 늘리지 말고, 독자가 더 보고 싶을 만한 내용이 빠진 지점을 찾아 주세요.\n\n[작품 기준]\n${criteria||'별도 기준 없음'}\n\n[검토 항목]\n- 감정 변화의 원인이나 여운이 너무 짧은 곳\n- 관계가 움직일 수 있는 작은 행동/대화\n- 생활·직업·공간의 현실 디테일이 필요한 곳\n- 사건 A→B 사이 연결이 급한 곳\n- 캐릭터를 보여줄 선택이나 행동이 빠진 곳\n- 이미 존재하는 설정·복선을 자연스럽게 재활용할 자리\n\n[중요]\n새 설정을 함부로 만들지 말고, 억지 감정이나 의미 없는 일상으로 분량을 채우지 마세요. 먼저 보강할 필요가 있는지 판단하고 필요한 곳에만 아이디어를 제안하세요. 아직 본문을 대신 써버리지 마세요.\n\n[원고]\n${text}`}
function autoSortCriteria(raw:string){const lines=raw.split(/\r?\n/).map(x=>x.replace(/^[-*•\s]+/,'').trim()).filter(Boolean);const groups:{[k:string]:string[]}={문체·톤:[],캐릭터:[],설정·연속성:[],감정·관계:[],금지·주의:[],기타:[]};for(const line of lines){if(/캐릭터|인물|성격|말투|호칭|이자람|류도겸|주인공/.test(line))groups['캐릭터'].push(line);else if(/설정|연속|시간|나이|직업|장소|세계관|오류|정합/.test(line))groups['설정·연속성'].push(line);else if(/감정|관계|호감|텐션|슬로우|속도|여운/.test(line))groups['감정·관계'].push(line);else if(/금지|주의|지양|싫|불필요|과한|하지 말|금물|AI스러|중복|반복/.test(line))groups['금지·주의'].push(line);else if(/문체|문장|서술|톤|설명|대사|리듬|시점/.test(line))groups['문체·톤'].push(line);else groups['기타'].push(line)}return groups}
function criteriaText(p:Project){const c=p.criteria||{};const raw=c['검수 기준집 원문']||'';const sections=['문체·톤','캐릭터','설정·연속성','감정·관계','금지·주의','기타'].map(k=>c[k]?`[${k}]\n${c[k]}`:'').filter(Boolean).join('\n\n');return sections||raw}
export default function WriterV3(){
 const [ws,setWs]=useState<Workspace|null>(null),[notice,setNotice]=useState('불러오는 중'),[stage,setStage]=useState<Stage>('polish'),[finding,setFinding]=useState<Finding|null>(null),[selection,setSelection]=useState(''),[prompt,setPrompt]=useState(''),[leftOpen,setLeftOpen]=useState(false),[rightOpen,setRightOpen]=useState(false),[leftId,setLeftId]=useState(''),[rightId,setRightId]=useState(''),[criteriaOpen,setCriteriaOpen]=useState(false);
 const rev=useRef(0),timer=useRef<number|undefined>(undefined);
 useEffect(()=>{loadWorkspace().then(r=>{rev.current=r.revision;setWs(r.workspace);setNotice('이 브라우저에 저장됨')}).catch(e=>setNotice('불러오기 실패: '+e))},[]);
 useEffect(()=>{if(!ws)return;window.clearTimeout(timer.current);setNotice('저장 대기');timer.current=window.setTimeout(async()=>{try{rev.current=await saveWorkspace(ws,rev.current);setNotice('이 브라우저에 저장됨')}catch(e){setNotice('저장 실패: '+e)}},500);return()=>window.clearTimeout(timer.current)},[ws]);
 const p=ws?.projects.find(x=>x.id===ws.activeId);const ordered=p?sortedSegments(p):[];const activeId=leftId||p?.selectedId||ordered[0]?.id||'';const s=p?.segments.find(x=>x.id===activeId);const ai=p?.segments.find(x=>x.id===(rightId||activeId));
 useEffect(()=>{if(!p)return;const first=p.selectedId||sortedSegments(p)[0]?.id||'';setLeftId(first);setRightId(first)},[p?.id]);
 const working=s?.final||s?.original||'';const findings=useMemo(()=>p?repeatFindings(working,p.repeat,p.threshold):[],[working,p?.repeat,p?.threshold]);const bannedFindings=useMemo(()=>p?phraseFindings(working,`${p.banned}\n${p.caution}`):[],[working,p?.banned,p?.caution]);const projectChars=p?ordered.reduce((n,x)=>n+count(x.final||x.original),0):0;const currentCriteria=p?criteriaText(p):'';
 const changeProject=(fn:(p:Project)=>Project)=>setWs(w=>{if(!w||!p)return w;return{...w,projects:w.projects.map(x=>x.id===p.id?{...fn(x),updatedAt:now()}:x)}});
 const editSegment=(id:string,mode:Mode,value:string)=>changeProject(q=>({...q,segments:q.segments.map(x=>x.id===id?{...x,[mode]:value}:x)}));
 const chooseOriginal=(id:string)=>{setLeftId(id);changeProject(q=>({...q,selectedId:id}));const t=p?.segments.find(x=>x.id===id);const match=p?.segments.find(x=>x.title.trim()===t?.title.trim()&&x.expanded);if(match)setRightId(match.id);setFinding(null);setPrompt('')};
 const saveNow=async()=>{if(!ws)return;window.clearTimeout(timer.current);try{rev.current=await saveWorkspace(ws,rev.current);setNotice('다듬는 원고 저장 완료')}catch(e){setNotice('저장 실패: '+e)}};
 const importFiles=async(files:FileList|null,mode:'original'|'expanded')=>{if(!files?.length||!p)return;const list=[...files].sort(naturalSort);let first='';let next=[...p.segments];const imports=[...p.imports];for(const f of list){const raw=await f.text(),base=fileTitle(f.name),parts=splitText(raw,base,'heading');imports.push({id:crypto.randomUUID(),title:f.name,text:raw,date:now()});for(const part of parts){let target=next.find(x=>x.title.trim()===part.title.trim());if(!target){target={...blankSegment(part.title,'회차','')};next.push(target)}target={...target,[mode]:part.text};if(mode==='original'&&!target.final)target.final=part.text;next=next.map(x=>x.id===target!.id?target!:x);if(!first)first=target.id}}next.sort((a,b)=>collator.compare(a.title,b.title));changeProject(q=>({...q,segments:next,selectedId:mode==='original'?(first||q.selectedId):q.selectedId,imports}));if(mode==='original'&&first)setLeftId(first);if(mode==='expanded'&&first)setRightId(first);setNotice(`${list.length}개 ${mode==='original'?'원본':'AI 확장본'} 파일을 가져왔어요. 회차는 숫자 기준으로 정렬됩니다.`)};
 const pasteText=(mode:'original'|'expanded')=>{const raw=window.prompt(mode==='original'?'원본 내용을 붙여넣으세요.':'AI 확장본 내용을 붙여넣으세요.');if(!raw?.trim())return;const title=window.prompt('회차/원고 이름',s?.title||'새 원고')?.trim()||'새 원고';let target=p?.segments.find(x=>x.title===title);if(!target)target={...blankSegment(title,'회차','')};const value={...target,[mode]:raw,...(mode==='original'&&!target.final?{final:raw}:{})};changeProject(q=>({...q,segments:[...q.segments.filter(x=>x.id!==value.id),value].sort((a,b)=>collator.compare(a.title,b.title)),selectedId:mode==='original'?value.id:q.selectedId}));mode==='original'?setLeftId(value.id):setRightId(value.id)};
 const importCriteria=async(files:FileList|null)=>{const f=files?.[0];if(!f||!p)return;const raw=await f.text();const groups=autoSortCriteria(raw);changeProject(q=>({...q,criteria:{...q.criteria,'검수 기준집 원문':raw,...Object.fromEntries(Object.entries(groups).map(([k,v])=>[k,v.join('\n')]))}}));setCriteriaOpen(true);setNotice('기준집을 불러와 항목별로 자동 정리했어요')};
 const organizeCriteria=()=>{if(!p)return;const raw=p.criteria?.['검수 기준집 원문']||'';const groups=autoSortCriteria(raw);changeProject(q=>({...q,criteria:{...q.criteria,...Object.fromEntries(Object.entries(groups).map(([k,v])=>[k,v.join('\n')]))}}));setNotice('기준집을 항목별로 다시 정리했어요')};
 const copyPrompt=async(x:string)=>{await navigator.clipboard.writeText(x);setPrompt(x);setNotice('GPT 요청문을 복사했어요')};
 if(!ws)return <main className="v3"><p>{notice}</p></main>;
 return <div className="v3"><header className="v3-head"><div><b>장편소설 작업실 v3</b><small>원본 → AI 확장 → 다듬기 → 1차 검수 → 장면 보강 → 최종본</small></div><span>{notice}</span></header>
 <div className="v3-project"><label>작품 <select value={ws.activeId} onChange={e=>{setWs(w=>w&&({...w,activeId:e.target.value}));setLeftId('');setRightId('')}}><option value="">작품 선택</option>{ws.projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{p&&<><strong>전체 {projectChars.toLocaleString()}자</strong><div className="import-group"><label className="v3-file">원본 파일 불러오기<input multiple type="file" accept=".txt,.md,text/plain,text/markdown" onChange={e=>{void importFiles(e.target.files,'original');e.currentTarget.value=''}}/></label><button onClick={()=>pasteText('original')}>원본 직접 넣기</button></div><div className="import-group"><label className="v3-file ai">AI 확장본 불러오기<input multiple type="file" accept=".txt,.md,text/plain,text/markdown" onChange={e=>{void importFiles(e.target.files,'expanded');e.currentTarget.value=''}}/></label><button onClick={()=>pasteText('expanded')}>AI 확장본 직접 넣기</button></div></>}</div>
 {!p?<section className="v3-empty"><h2>새 작품부터 시작해도 되고, 이미 쓴 작품을 가져와도 돼요.</h2><button className="primary" onClick={()=>{const name=window.prompt('새 작품 이름');if(!name?.trim())return;const q=blankProject(name);setWs(w=>w&&({...w,projects:[...w.projects,q],activeId:q.id}))}}>새 작품 만들기</button></section>:
 <div className={`v3-three ${leftOpen?'left-open':'left-closed'} ${rightOpen?'right-open':'right-closed'}`}>
 <aside className="side original-side"><button className="side-toggle" onClick={()=>setLeftOpen(v=>!v)}>☰ <span>{leftOpen?'원고 접기':'원고'}</span></button>{leftOpen&&<><h3>원본 선택</h3><p className="v3-help">회차를 눌러 작업 기준 원고를 바꿉니다.</p>{ordered.filter(x=>x.original).map(x=><button key={x.id} className={x.id===activeId?'on':''} onClick={()=>chooseOriginal(x.id)}><b>{x.title}</b><small>{count(x.original).toLocaleString()}자</small></button>)}</>}</aside>
 <main>{!s?<section className="v3-empty"><h2>원고를 가져오거나 직접 넣어 시작하세요.</h2></section>:<><section className="v3-toolbar"><div><h2>{s.title}</h2><span className="counts">원본 {count(s.original).toLocaleString()}자 · AI {count(ai?.expanded||'').toLocaleString()}자 · 수정본 {count(s.final).toLocaleString()}자</span></div><div className="stage-tabs"><button className={stage==='polish'?'on':''} onClick={()=>setStage('polish')}>① 비교·다듬기</button><button className={stage==='review'?'on':''} onClick={()=>setStage('review')}>② 1차 검수</button><button className={stage==='quality'?'on':''} onClick={()=>setStage('quality')}>③ 장면 보강</button></div></section>
 {stage==='polish'&&<><section className="compare"><article><div className="pane-head"><b>원본 · {s.title}</b><span>{count(s.original).toLocaleString()}자</span></div><textarea value={s.original} onChange={e=>editSegment(s.id,'original',e.target.value)} /></article><article><div className="pane-head"><b>AI 확장본 · {ai?.title||'선택 안 됨'}</b><span>{count(ai?.expanded||'').toLocaleString()}자</span></div><textarea value={ai?.expanded||''} onChange={e=>ai&&editSegment(ai.id,'expanded',e.target.value)} placeholder="오른쪽에서 AI 확장본 회차를 선택하세요." /></article></section><section className="polish"><div className="pane-head"><div><b>다듬는 원고</b><small>원본/AI는 그대로 두고 수정본만 별도 저장합니다.</small></div><div><button onClick={()=>{if(confirm('수정본을 현재 원본으로 바꿀까요?'))editSegment(s.id,'final',s.original)}}>원본에서 시작</button><button onClick={()=>{if(ai&&confirm('수정본을 현재 AI 확장본으로 바꿀까요?'))editSegment(s.id,'final',ai.expanded)}}>AI에서 시작</button></div></div><textarea value={s.final} onChange={e=>editSegment(s.id,'final',e.target.value)} onSelect={e=>{const t=e.currentTarget;setSelection(t.value.slice(t.selectionStart,t.selectionEnd))}}/><div className="v3-editor-foot"><button className="primary manual-save" onClick={saveNow}>다듬는 원고 저장</button><span>수정본 {count(s.final).toLocaleString()}자 · 선택 {selection.length.toLocaleString()}자</span>{selection&&<button onClick={()=>copyPrompt(reviewPrompt('선택한 부분 검토',selection,s.final,currentCriteria))}>선택 부분 GPT 검토</button>}</div></section></>}
 {stage==='review'&&<section className="v3-review"><div className="v3-title"><div><h3>1차 검수</h3><p><b>검수 대상: 다듬는 원고</b> · 반복뿐 아니라 작품 기준집까지 함께 봅니다.</p></div><span>{findings.length+bannedFindings.length}개 로컬 후보</span></div>
 <div className="criteria-bar"><div><b>작품 검수 기준집</b><small>{currentCriteria?`등록됨 · ${currentCriteria.length.toLocaleString()}자`:'아직 등록되지 않음'}</small></div><div><label className="v3-file criteria-file">기준집 파일 넣기<input type="file" accept=".txt,.md,text/plain,text/markdown" onChange={e=>{void importCriteria(e.target.files);e.currentTarget.value=''}}/></label><button onClick={()=>setCriteriaOpen(v=>!v)}>{criteriaOpen?'기준집 닫기':'기준집 열기'}</button></div></div>
 {criteriaOpen&&<div className="criteria-panel"><label>기준집 원문<textarea value={p.criteria?.['검수 기준집 원문']||''} onChange={e=>changeProject(q=>({...q,criteria:{...q.criteria,'검수 기준집 원문':e.target.value}}))} placeholder="여기에 평소 GPT에게 주던 검수 기준, 싫어하는 문체, 캐릭터 원칙, 금지사항 등을 통째로 붙여넣으세요."/></label><div className="criteria-actions"><button className="primary" onClick={organizeCriteria}>기준 자동 정리</button><span>문체·톤 / 캐릭터 / 설정·연속성 / 감정·관계 / 금지·주의로 나눕니다.</span></div><div className="criteria-grid">{['문체·톤','캐릭터','설정·연속성','감정·관계','금지·주의','기타'].map(k=><label key={k}><b>{k}</b><textarea value={p.criteria?.[k]||''} onChange={e=>changeProject(q=>({...q,criteria:{...q.criteria,[k]:e.target.value}}))}/></label>)}</div><div className="criteria-grid compact"><label><b>금지 표현</b><textarea value={p.banned} onChange={e=>changeProject(q=>({...q,banned:e.target.value}))} placeholder="예: 심장이 쿵 내려앉았다, 숨을 삼켰다"/></label><label><b>주의 표현</b><textarea value={p.caution} onChange={e=>changeProject(q=>({...q,caution:e.target.value}))}/></label><label><b>반복 표현 묶음</b><textarea value={p.repeat} onChange={e=>changeProject(q=>({...q,repeat:e.target.value}))} placeholder="고개를 숙였다/고개를 내렸다"/></label></div></div>}
 <div className="review-actions"><button className="primary big" disabled={!currentCriteria} onClick={()=>copyPrompt(criteriaReviewPrompt(working,currentCriteria))}>기준집으로 이 회차 심층 검수 요청</button><span>캐릭터·감정속도·설정·문체처럼 단순 검색으로 못 잡는 항목까지 기준집을 붙여 검토합니다.</span></div>
 {bannedFindings.length>0&&<div className="review-block"><h4>금지·주의 표현 확인</h4>{bannedFindings.map(f=><button key={`b-${f.term}`} onClick={()=>{setFinding(f);setPrompt(reviewPrompt(`기준집 금지·주의 표현 ${f.term}`,f.snippets[0]||'',working,currentCriteria))}}>{f.term} · {f.count}회</button>)}</div>}
 <div className="review-block"><h4>반복 단어·표현 후보</h4>{!findings.length?<p className="v3-ok">현재 기준에서 두드러진 반복 후보가 없어요.</p>:findings.map(f=><button key={f.term} onClick={()=>{setFinding(f);setPrompt(reviewPrompt(`반복 표현 ${f.term} ${f.count}회`,f.snippets[0]||'',working,currentCriteria))}}>{f.term} · {f.count}회</button>)}</div>
 {finding&&<div className="inline-fix"><h4>{finding.term}</h4>{finding.snippets.map((x,i)=><blockquote key={i}>{x}</blockquote>)}<div className="fix-actions"><button onClick={()=>setFinding(null)}>그대로 두기</button><button onClick={()=>setStage('polish')}>직접 수정</button><button className="primary" onClick={()=>copyPrompt(prompt)}>GPT 수정 요청</button></div></div>}</section>}
 {stage==='quality'&&<section className="quality"><h3>장면 보강 · 퀄리티 검토</h3><p>감정·관계·생활 디테일·사건 연결·캐릭터·복선 중 빠진 부분만 찾습니다.</p><button className="primary big" onClick={()=>copyPrompt(qualityPrompt(s.final||s.original,currentCriteria))}>이 회차 장면 보강 검토 요청 만들기</button>{prompt&&<textarea className="v3-prompt" value={prompt} onChange={e=>setPrompt(e.target.value)}/>}</section>}</>}</main>
 <aside className="side ai-side"><button className="side-toggle" onClick={()=>setRightOpen(v=>!v)}><span>{rightOpen?'AI 접기':'AI'}</span> ☰</button>{rightOpen&&<><h3>AI 확장본 선택</h3><p className="v3-help">원본과 다른 회차도 따로 비교할 수 있어요.</p>{ordered.filter(x=>x.expanded).map(x=><button key={x.id} className={x.id===(rightId||activeId)?'on':''} onClick={()=>setRightId(x.id)}><b>{x.title}</b><small>{count(x.expanded).toLocaleString()}자</small></button>)}</>}</aside>
 </div>}
 </div>;
}
