import { useEffect, useMemo, useRef, useState } from 'react';
import { blankProject, blankSegment, now, splitText, type Project, type Workspace } from './model';
import { loadWorkspace, saveWorkspace } from './storage';
import './writer-v3.css';

type Mode='original'|'expanded'|'final';
type Stage='polish'|'review'|'quality';
type Finding={term:string;count:number;snippets:string[]};
const count=(s:string)=>s.length;
const esc=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const fileTitle=(name:string)=>name.replace(/\.[^.]+$/,'');
const collator=new Intl.Collator('ko',{numeric:true,sensitivity:'base'});
const naturalSort=(a:File,b:File)=>collator.compare(a.name,b.name);
const sortedSegments=(p:Project)=>[...p.segments].filter(x=>x.kind==='회차'||x.kind==='장면').sort((a,b)=>collator.compare(a.title,b.title));
function repeatFindings(text:string,custom:string,threshold=3):Finding[]{const terms=new Set(custom.split(/[\n,/]/).map(x=>x.trim()).filter(x=>x.length>=2));const tokens=text.match(/[가-힣A-Za-z]{2,}/g)||[],freq=new Map<string,number>();tokens.forEach(t=>freq.set(t,(freq.get(t)||0)+1));[...freq].filter(([,n])=>n>=Math.max(4,threshold)).sort((a,b)=>b[1]-a[1]).slice(0,24).forEach(([t])=>terms.add(t));return [...terms].map(term=>{const re=new RegExp(esc(term),'g'),n=(text.match(re)||[]).length;if(n<threshold)return null;const snippets:string[]=[];let m:RegExpExecArray|null;while((m=re.exec(text))&&snippets.length<5){snippets.push(text.slice(Math.max(0,m.index-50),Math.min(text.length,m.index+term.length+60)).replace(/\s+/g,' '));if(re.lastIndex===m.index)re.lastIndex++;}return{term,count:n,snippets}}).filter(Boolean).sort((a,b)=>b!.count-a!.count) as Finding[]}
function reviewPrompt(term:string,selected:string,text:string){const target=selected.trim()||term,i=selected.trim()?text.indexOf(selected):text.indexOf(term),a=Math.max(0,i-600),b=Math.min(text.length,(i<0?0:i+target.length)+600);return `장편소설 퇴고 중입니다. 아래 부분을 보수적으로 검토해 주세요.\n\n[확인 이유]\n${term}\n\n[수정 대상]\n${target}\n\n[앞뒤 문맥]\n${text.slice(a,b)}\n\n[원칙]\n- 무조건 수정하지 말고 실제로 거슬릴 때만 수정\n- 사건, 설정, 캐릭터 성격과 감정 진행 속도 유지\n- 과한 감정 추가, 새 설정 추가, 전면 재작성 금지\n- 원문 유지가 더 좋다면 유지 추천이라고 명시\n\n[답변]\n1. 수정 필요 여부\n2. 이유\n3. 필요할 때만 수정안 1~3개`}
function qualityPrompt(text:string){return `아래 장편소설 원고에서 단순히 분량을 늘리지 말고, 독자가 더 보고 싶을 만한 내용이 빠진 지점을 찾아 주세요.\n\n[검토 항목]\n- 감정 변화의 원인이나 여운이 너무 짧은 곳\n- 관계가 움직일 수 있는 작은 행동/대화\n- 생활·직업·공간의 현실 디테일이 필요한 곳\n- 사건 A→B 사이 연결이 급한 곳\n- 캐릭터를 보여줄 선택이나 행동이 빠진 곳\n- 이미 존재하는 설정·복선을 자연스럽게 재활용할 자리\n\n[중요]\n새 설정을 함부로 만들지 말고, 억지 감정이나 의미 없는 일상으로 분량을 채우지 마세요. 먼저 보강할 필요가 있는지 판단하고 필요한 곳에만 아이디어를 제안하세요. 아직 본문을 대신 써버리지 마세요.\n\n[원고]\n${text}`}
export default function WriterV3(){
 const [ws,setWs]=useState<Workspace|null>(null),[notice,setNotice]=useState('불러오는 중'),[stage,setStage]=useState<Stage>('polish'),[finding,setFinding]=useState<Finding|null>(null),[selection,setSelection]=useState(''),[prompt,setPrompt]=useState(''),[leftOpen,setLeftOpen]=useState(false),[rightOpen,setRightOpen]=useState(false),[leftId,setLeftId]=useState(''),[rightId,setRightId]=useState('');
 const rev=useRef(0),timer=useRef<number|undefined>(undefined);
 useEffect(()=>{loadWorkspace().then(r=>{rev.current=r.revision;setWs(r.workspace);setNotice('이 브라우저에 저장됨')}).catch(e=>setNotice('불러오기 실패: '+e))},[]);
 useEffect(()=>{if(!ws)return;window.clearTimeout(timer.current);setNotice('저장 대기');timer.current=window.setTimeout(async()=>{try{rev.current=await saveWorkspace(ws,rev.current);setNotice('이 브라우저에 저장됨')}catch(e){setNotice('저장 실패: '+e)}},500);return()=>window.clearTimeout(timer.current)},[ws]);
 const p=ws?.projects.find(x=>x.id===ws.activeId);const ordered=p?sortedSegments(p):[];const activeId=leftId||p?.selectedId||ordered[0]?.id||'';const s=p?.segments.find(x=>x.id===activeId);const ai=p?.segments.find(x=>x.id===(rightId||activeId));
 useEffect(()=>{if(!p)return;const first=p.selectedId||sortedSegments(p)[0]?.id||'';setLeftId(first);setRightId(first)},[p?.id]);
 const working=s?.final||s?.original||'';const findings=useMemo(()=>p?repeatFindings(working,p.repeat,p.threshold):[],[working,p?.repeat,p?.threshold]);const projectChars=p?ordered.reduce((n,x)=>n+count(x.final||x.original),0):0;
 const changeProject=(fn:(p:Project)=>Project)=>setWs(w=>{if(!w||!p)return w;return{...w,projects:w.projects.map(x=>x.id===p.id?{...fn(x),updatedAt:now()}:x)}});
 const editSegment=(id:string,mode:Mode,value:string)=>changeProject(q=>({...q,segments:q.segments.map(x=>x.id===id?{...x,[mode]:value}:x)}));
 const chooseOriginal=(id:string)=>{setLeftId(id);changeProject(q=>({...q,selectedId:id}));const t=p?.segments.find(x=>x.id===id);const match=p?.segments.find(x=>x.title.trim()===t?.title.trim()&&x.expanded);if(match)setRightId(match.id);setFinding(null);setPrompt('')};
 const saveNow=async()=>{if(!ws)return;window.clearTimeout(timer.current);try{rev.current=await saveWorkspace(ws,rev.current);setNotice('다듬는 원고 저장 완료')}catch(e){setNotice('저장 실패: '+e)}};
 const importFiles=async(files:FileList|null,mode:'original'|'expanded')=>{if(!files?.length||!p)return;const list=[...files].sort(naturalSort);let first='';let next=[...p.segments];const imports=[...p.imports];for(const f of list){const raw=await f.text(),base=fileTitle(f.name),parts=splitText(raw,base,'heading');imports.push({id:crypto.randomUUID(),title:f.name,text:raw,date:now()});for(const part of parts){let target=next.find(x=>x.title.trim()===part.title.trim());if(!target){target={...blankSegment(part.title,'회차','')};next.push(target)}target={...target,[mode]:part.text};if(mode==='original'&&!target.final)target.final=part.text;next=next.map(x=>x.id===target!.id?target!:x);if(!first)first=target.id}}next.sort((a,b)=>collator.compare(a.title,b.title));changeProject(q=>({...q,segments:next,selectedId:mode==='original'?(first||q.selectedId):q.selectedId,imports}));if(mode==='original'&&first)setLeftId(first);if(mode==='expanded'&&first)setRightId(first);setNotice(`${list.length}개 ${mode==='original'?'원본':'AI 확장본'} 파일을 가져왔어요. 회차는 숫자 기준으로 정렬됩니다.`)};
 const pasteText=(mode:'original'|'expanded')=>{const raw=window.prompt(mode==='original'?'원본 내용을 붙여넣으세요.':'AI 확장본 내용을 붙여넣으세요.');if(!raw?.trim())return;const title=window.prompt('회차/원고 이름',s?.title||'새 원고')?.trim()||'새 원고';let target=p?.segments.find(x=>x.title===title);if(!target)target={...blankSegment(title,'회차','')};const value={...target,[mode]:raw,...(mode==='original'&&!target.final?{final:raw}:{})};changeProject(q=>({...q,segments:[...q.segments.filter(x=>x.id!==value.id),value].sort((a,b)=>collator.compare(a.title,b.title)),selectedId:mode==='original'?value.id:q.selectedId}));mode==='original'?setLeftId(value.id):setRightId(value.id)};
 const copyPrompt=async(x:string)=>{await navigator.clipboard.writeText(x);setPrompt(x);setNotice('GPT 요청문을 복사했어요')};
 if(!ws)return <main className="v3"><p>{notice}</p></main>;
 return <div className="v3"><header className="v3-head"><div><b>장편소설 작업실 v3</b><small>원본 → AI 확장 → 다듬기 → 1차 검수 → 장면 보강 → 최종본</small></div><span>{notice}</span></header>
 <div className="v3-project"><label>작품 <select value={ws.activeId} onChange={e=>{setWs(w=>w&&({...w,activeId:e.target.value}));setLeftId('');setRightId('')}}><option value="">작품 선택</option>{ws.projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{p&&<><strong>전체 {projectChars.toLocaleString()}자</strong><div className="import-group"><label className="v3-file">원본 파일 불러오기<input multiple type="file" accept=".txt,.md,text/plain,text/markdown" onChange={e=>{void importFiles(e.target.files,'original');e.currentTarget.value=''}}/></label><button onClick={()=>pasteText('original')}>원본 직접 넣기</button></div><div className="import-group"><label className="v3-file ai">AI 확장본 불러오기<input multiple type="file" accept=".txt,.md,text/plain,text/markdown" onChange={e=>{void importFiles(e.target.files,'expanded');e.currentTarget.value=''}}/></label><button onClick={()=>pasteText('expanded')}>AI 확장본 직접 넣기</button></div></>}</div>
 {!p?<section className="v3-empty"><h2>새 작품부터 시작해도 되고, 이미 쓴 작품을 가져와도 돼요.</h2><button className="primary" onClick={()=>{const name=window.prompt('새 작품 이름');if(!name?.trim())return;const q=blankProject(name);setWs(w=>w&&({...w,projects:[...w.projects,q],activeId:q.id}))}}>새 작품 만들기</button></section>:
 <div className={`v3-three ${leftOpen?'left-open':'left-closed'} ${rightOpen?'right-open':'right-closed'}`}>
 <aside className="side original-side"><button className="side-toggle" onClick={()=>setLeftOpen(v=>!v)}>☰ <span>{leftOpen?'원고 접기':'원고'}</span></button>{leftOpen&&<><h3>원본 선택</h3><p className="v3-help">회차를 눌러 작업 기준 원고를 바꿉니다.</p>{ordered.filter(x=>x.original).map(x=><button key={x.id} className={x.id===activeId?'on':''} onClick={()=>chooseOriginal(x.id)}><b>{x.title}</b><small>{count(x.original).toLocaleString()}자</small></button>)}</>}</aside>
 <main>{!s?<section className="v3-empty"><h2>원고를 가져오거나 직접 넣어 시작하세요.</h2></section>:<><section className="v3-toolbar"><div><h2>{s.title}</h2><span className="counts">원본 {count(s.original).toLocaleString()}자 · AI {count(ai?.expanded||'').toLocaleString()}자 · 수정본 {count(s.final).toLocaleString()}자</span></div><div className="stage-tabs"><button className={stage==='polish'?'on':''} onClick={()=>setStage('polish')}>① 비교·다듬기</button><button className={stage==='review'?'on':''} onClick={()=>setStage('review')}>② 1차 검수</button><button className={stage==='quality'?'on':''} onClick={()=>setStage('quality')}>③ 장면 보강</button></div></section>
 {stage==='polish'&&<><section className="compare"><article><div className="pane-head"><b>원본 · {s.title}</b><span>{count(s.original).toLocaleString()}자</span></div><textarea value={s.original} onChange={e=>editSegment(s.id,'original',e.target.value)} /></article><article><div className="pane-head"><b>AI 확장본 · {ai?.title||'선택 안 됨'}</b><span>{count(ai?.expanded||'').toLocaleString()}자</span></div><textarea value={ai?.expanded||''} onChange={e=>ai&&editSegment(ai.id,'expanded',e.target.value)} placeholder="오른쪽에서 AI 확장본 회차를 선택하세요." /></article></section><section className="polish"><div className="pane-head"><div><b>다듬는 원고</b><small>원본/AI는 그대로 두고 수정본만 별도 저장합니다.</small></div><div><button onClick={()=>{if(confirm('수정본을 현재 원본으로 바꿀까요?'))editSegment(s.id,'final',s.original)}}>원본에서 시작</button><button onClick={()=>{if(ai&&confirm('수정본을 현재 AI 확장본으로 바꿀까요?'))editSegment(s.id,'final',ai.expanded)}}>AI에서 시작</button></div></div><textarea value={s.final} onChange={e=>editSegment(s.id,'final',e.target.value)} onSelect={e=>{const t=e.currentTarget;setSelection(t.value.slice(t.selectionStart,t.selectionEnd))}}/><div className="v3-editor-foot"><button className="primary manual-save" onClick={saveNow}>다듬는 원고 저장</button><span>수정본 {count(s.final).toLocaleString()}자 · 선택 {selection.length.toLocaleString()}자</span>{selection&&<button onClick={()=>copyPrompt(reviewPrompt('선택한 부분 검토',selection,s.final))}>선택 부분 GPT 검토</button>}</div></section></>}
 {stage==='review'&&<section className="v3-review"><div className="v3-title"><div><h3>1차 검수</h3><p>찾았다고 전부 고치지 않고 실제로 거슬리는 곳만 확인합니다.</p></div><span>{findings.length}개 후보</span></div>{findings.map(f=><button key={f.term} onClick={()=>{setFinding(f);setPrompt(reviewPrompt(`반복 표현 ${f.term} ${f.count}회`,f.snippets[0]||'',s.final))}}>{f.term} · {f.count}회</button>)}{finding&&<div className="inline-fix"><h4>{finding.term}</h4>{finding.snippets.map((x,i)=><blockquote key={i}>{x}</blockquote>)}<div className="fix-actions"><button onClick={()=>setFinding(null)}>그대로 두기</button><button onClick={()=>setStage('polish')}>직접 수정</button><button className="primary" onClick={()=>copyPrompt(prompt)}>GPT 수정 요청</button></div></div>}</section>}
 {stage==='quality'&&<section className="quality"><h3>장면 보강 · 퀄리티 검토</h3><p>감정·관계·생활 디테일·사건 연결·캐릭터·복선 중 빠진 부분만 찾습니다.</p><button className="primary big" onClick={()=>copyPrompt(qualityPrompt(s.final||s.original))}>이 회차 장면 보강 검토 요청 만들기</button>{prompt&&<textarea className="v3-prompt" value={prompt} onChange={e=>setPrompt(e.target.value)}/>}</section>}</>}</main>
 <aside className="side ai-side"><button className="side-toggle" onClick={()=>setRightOpen(v=>!v)}><span>{rightOpen?'AI 접기':'AI'}</span> ☰</button>{rightOpen&&<><h3>AI 확장본 선택</h3><p className="v3-help">원본과 다른 회차도 따로 비교할 수 있어요.</p>{ordered.filter(x=>x.expanded).map(x=><button key={x.id} className={x.id===(rightId||activeId)?'on':''} onClick={()=>setRightId(x.id)}><b>{x.title}</b><small>{count(x.expanded).toLocaleString()}자</small></button>)}</>}</aside>
 </div>}
 </div>;
}
